Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -59,7 +59,7 @@ jobs:
       run: |
         cd immortalwrt
         make clean
-        make download -j8 || make download -j1 V=s
+        make download -j8 
         make -j$(nproc)
 
         
@@ -67,21 +67,30 @@ jobs:
 #      run: |
 #        bash ../sh/diy-part2.sh
 
-        
+    - name: 文件检查
+      run: |
+          FIRMWARE_PATH="bin/targets/armvirt/64/immortalwrt-rockchip-armv8-friendlyarm_nanopi-r3s-squashfs-sysupgrade.img.gz"
+          if [ ! -f "$FIRMWARE_PATH" ]; then
+            echo "Firmware file not found!"
+            exit 1
+          else
+            echo "Firmware file found: $FIRMWARE_PATH"
+          fi
+
+
     - name: 按照时间戳重命名
       run: |
-        # 获取当前日期时间
         DATE=$(date +"%Y%m%d%H%M%S")
         FIRMWARE_PATH="bin/targets/armvirt/64/immortalwrt-rockchip-armv8-friendlyarm_nanopi-r3s-squashfs-sysupgrade.img.gz"
         NEW_FIRMWARE_NAME="${DATE}-r3s-squashfs-sysupgrade.img.gz"
-        # 重命名固件
         mv "$FIRMWARE_PATH" "bin/targets/armvirt/64/$NEW_FIRMWARE_NAME"
         echo "Renamed firmware to: $NEW_FIRMWARE_NAME"
 
-    - name: 上传到releases
+
+     - name: 上传重命名后的固件
       uses: actions/upload-artifact@v2
       with:
         name: firmware
         path: "bin/targets/armvirt/64/${NEW_FIRMWARE_NAME}"
-        retention-days: 5
-        if-no-files-found: error
+         retention-days: 5
+         if-no-files-found: error
